name: main_workflow

on:
  push:
    branches:
      - main  # Rama que va a utilitzar els jobs

permissions:
  contents: write

jobs: #Definim cada job y el sistema que utilitzará amb els pasos
  # Linter_job: #Chequea el codi y ens trau els errors que pot haver
  #   runs-on: ubuntu-latest  
  #   steps:
  #     - name: Checkout codi
  #       uses: actions/checkout@v2  # #Clona el codi font per a poder trobar els errors

  #     - name: Configuració Node.js
  #       uses: actions/setup-node@v2  # Configurem nodejs
  #       with:
  #         node-version: '16'  

  #     - name: Install dependencies
  #       run: npm install  # Instala les dependencies

  #     - name: Run linter
  #       run: npm run lint || exit 1  # Ejecuta el linter y si hi ha error para
        
        # TEST Cypress: verifica que la aplicació web funcione perfectament
  Cypress_job:
    runs-on: ubuntu-latest
    # needs: Linter_job
    steps:
      - name: Checkout codi
        uses: actions/checkout@v4

      - name: Configuració Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-actions@v5
        with: 
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypress
      - name: crear result.txt
        run: echo ${{steps.cypress.outcome}} > result.txt

      - name: Crear artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: results.txt # Ruta al archivo 

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job  # Aquest job dependrà de Cypress_job
    steps:
      - name: Checkout codi
        uses: actions/checkout@v4
      
      - name: Install dependencies for custom action
        run: |
          cd ./update-readme-action
          npm install

      - name: Obtenir artefacte de Cypress
        uses: actions/download-artifact@v3
        with:
          name: cypress-results  # Nom de l'artefacte creat anteriorment

      - name: Generar output
        id: read-result
        run: echo "::set-output name=cypress_outcome::$(cat results.txt)"

      - name: Actualitzar el README.md
        uses: ./update-readme-action  # Cridem a la GitHub Action pròpia
        with:
          outcome: ${{ steps.read-result.outputs.cypress_outcome }}

      - name: "push Readme"
        uses: EndBug/add-and-commit@v9
        with: 
          add: "."
          author_name: "Jonathan Alcobendas"
          author_email: "jonathanAlcobendas@gmail.com"
          message: "Afegit a readme"
          push: true
  Deploy_job: #Deploy en plataforma Vercel
    runs-on: ubuntu-latest  
    needs: Cypress_job  
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 

      - name: Desplegar en Vercel
        uses: amondnet/vercel-action@v20  #Action per a desplegar en Vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}  #token secreto de Vercel
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}  #ID del proyecto en Vercel
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}  # ID de la organización en Vercel
          vercel_alias: ${{ secrets.VERCEL_ALIAS }}  # Alias del dominio

  Notification_job:
    runs-on: ubuntu-latest
    needs: [Cypress_job, Add_badge_job, Deploy_job]  #Necesitem tots els jobs anteriors afegir linter
    if: always()  # S' executa sempre encara que fallen altres jobs
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Send Notification Email
        uses: peter-evans/send-mail@v2
        with:
          server: smtp.gmail.com  # Servidor SMTP (Gmail)
          port: 587  # Puerto SMTP
          username: ${{ secrets.EMAIL_USERNAME }}  # Nombre de usuario secreto
          password: ${{ secrets.EMAIL_PASSWORD }}  # Contraseña secreto github
          to: ${{ secrets.EMAIL_RECIPIENT }}  # Dirección de correo secreto
          subject: "Resultat del workflow executat"
          body: |
            S'ha realitzat un push en la branca main que ha provocat l'execució del workflow {{ github.workflow }} amb els següents resultats:
            
            - **linter_job**: ${{ job.status }} 
            - **cypress_job**: ${{ needs.Cypress_job.result }} 
            - **add_badge_job**: ${{ needs.Add_badge_job.result }} 
            - **deploy_job**: ${{ needs.Deploy_job.result }}

  # update_readme_stats:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout codi
#       uses: actions/checkout@v2
# 
#     - name: Setup Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16'
# 
#     - name: Instalem dependencies
#       run: npm install
# 
#     - name: Generate Language Stats Image
#       run: |
#         curl -s https://raw.githubusercontent.com/anuraghazra/github-readme-stats/master/generated/languages.svg > languages.svg
#         git add languages.svg
#         git commit -m "Update language stats"
#         git push

