name: main_workflow

on:
  push:
    branches:
      - main  # Rama que va a utilitzar els jobs

jobs: #Definim cada job y el sistema que utilitzar치 amb els pasos
  Linter_job: #Chequea el codi y ens trau els errors que pot haver
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout codi
        uses: actions/checkout@v2  # #Clona el codi font per a poder trobar els errors

      - name: Configuraci칩 Node.js
        uses: actions/setup-node@v2  # Configurem nodejs
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install  # Instala les dependencies

      - name: Run linter
        run: npm run lint || exit 1  # Ejecuta el linter y si hi ha error para
        
        #TEST Cypress: verifica que la aplicaci칩 web funcione perfectament
  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - name: Checkout codi
        uses: actions/checkout@v2

      - name: Configuraci칩 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Iniciar el servidor #per a que funcione cypress iniciem el servidor
        run: npm run dev &
        env:
          CI: true

      - name: Iniciar Cypress tests
        run: npm run cypress -- --reporter=json > results.txt || true #fem que genere el txt

      - name: Crear artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: results.txt # Ruta al archivo 